### ISSUE TITLE
Not a `GLOB` Reference (latest release breakage)

### ISSUE THREAD

**Issue by GuiltyDolphin** [ingydotnet/yaml-libyaml-pm#38] opened 2016-02-21 09:22 UTC
We use `YAML::XS` quite a bit over on DuckDuckHack, but the most recent update (from `0.59` to `0.61`) has caused many tests to fail; the error message is consistently along the lines of:

![screenshot from 2016-02-21 09 07 21](https://cloud.githubusercontent.com/assets/8598426/13201856/07eab93c-d87b-11e5-9fce-7f8ec2b4534e.png)

I've had a quick look and it appears to be the changes introduces by #36, which changes from the `ref $filename eq 'GLOB'` check to `defined fileno($filename)`.

/cc @ingydotnet @lameventanas

**Comment by perlpunk** [comment] 2016-02-21 10:44
@GuiltyDolphin thanks, can you tell us what perl version you're running? I don't see any failures in the testers matrix.

**Comment by perlpunk** [comment] 2016-02-21 10:48
Also, the `t/HelpLine.t` test is not part of the YAML::XS test suite. Could you show us the relevant code, so that we can try to reproduce what's happening there?

**Comment by perlpunk** [comment] 2016-02-21 11:02
ok, found it out by searching github for HelpLine.t.
the filename is a Path::Class object. was able to reproduce it.
```
use Path::Class;
use YAML::XS qw/ LoadFile /;
my $file = file("t", "foo.yaml");
my $data = LoadFile($file);

```

**Comment by GuiltyDolphin** [comment] 2016-02-21 11:02
@perlpunk Sorry yeah, that's from our tests.

The code for the `HelpLine` file is at: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/HelpLine.pm

We use a `share` subroutine for locating the appropriate files, which is then used directly in `LoadFile`. The code for that can be found here: https://github.com/duckduckgo/duckduckgo/blob/master/lib/DDG/Meta/ShareDir.pm

Understandably we're not passing a *string* directly into the function - so if there isn't an easy fix I guess we can work around it.

**Comment by perlpunk** [comment] 2016-02-21 11:08
an easy workaround for the moment would be to do `LoadFile( "" . file(...) )` instead of `LoadFile( file(...) )`

but I guess we should make it work with Path::Class objects too, especially since it has been working before =)

**Comment by GuiltyDolphin** [comment] 2016-02-21 11:12
@perlpunk Yeah, that'd be great! What is the general release cycle for you guys? I could do a temporary fix until you're all sorted :dolphin: thanks!

**Comment by perlpunk** [comment] 2016-02-21 11:58
ok, I added a little fix that simply checks for Path::Class objects. Not really happy with that, though. There should be a more canonical way to check if something is a filehandle or not.
Created a pull request.
Wait for @ingydotnet to review

**Comment by GuiltyDolphin** [comment] 2016-02-21 12:01
@perlpunk Thanks again!

Yeah, Perl has her ways :wink: I'm sure there's something buried deep within her docs.

**Comment by perlpunk** [comment] 2016-02-21 12:32
Ok, created a new pull request, where I simply copied the code from File::Copy =)
This seems to be the cleanest solution to check for filehandles.

**Comment by perlpunk** [comment] 2016-02-21 13:10
Well, I just had the idea to try out the new Ref::Util https://github.com/p5pclub/ref-util from @xsawyerx

```perl
use Ref::Util qw/ is_globref is_ioref /;
return is_globref($var) || is_ioref($var);
```
Test suite succeeds!

**Comment by xsawyerx** [comment] 2016-02-21 13:12
Whoa! I'm honored!
@perlpunk++

**Comment by GuiltyDolphin** [comment] 2016-02-21 13:15
@perlpunk @xsawyerx Ooh... Nice. Might help with any other breakages too.

**Comment by perlpunk** [comment] 2016-02-21 13:26
I created another pull request #41 with Ref::Util. Now @ingydotnet should decide which one ;-)

**Comment by perlpunk** [comment] 2016-02-21 13:51
@xsawyerx is Ref::Util supposed to go into core at some point? =)

**Comment by xsawyerx** [comment] 2016-02-21 15:13
@perlpunk I haven't submitted it to be included in core. Do you think core is a better place for it?

**Comment by perlpunk** [comment] 2016-02-21 15:19
@xsawyerx given that we have List::Util, Scalar::Util, Hash::Util - yes, I think so

**Comment by xsawyerx** [comment] 2016-02-21 15:22
Originally Perl did have `Ref::Util`, I believe. A long long time ago. It was later merged into `Scalar::Util`. I had to ask Graham Barr for the namespace. :)

**Comment by perlpunk** [comment] 2016-02-21 19:21
I also thought about using `defined eval { fileno ... }`, and a user on perl-community.de also suggested it.
It would work for all the cases I can think of / are in the YAML::XS suite. But I'm not sure I like it. Opinions?

**Comment by xsawyerx** [comment] 2016-02-21 19:42
The way I use `eval` is:

````
eval {
    do_thing_that_might_crash();
} or do {
    my $error = $@;
    # do error handling
};
````

The reasons I wrote `Ref::Util` are:

1. Faster by not creating a string and comparing it to another string (it literally checks flags).
2. Faster by creating op codes (also because it's fun).
3. Avoid common mistake of typo (`ARRRAY`, `REGEX, `REGEXP` -- all wrong).
4. Avoid common mistake of using overloaded variables ("I can *act* like a hashref!") which then might fail because used in ways that fails the check.
5. Avoid common mistake of blessed packages (in which case you correctly need `Scalar::Util::reftype` which is still suffer previous clauses).

These reasons might not fit your reasons and you may find yourself not needing to use it.

**Comment by perlpunk** [comment] 2016-02-21 19:51
hmmmmm!
there is much more than one way for this.
```perl
use Scalar::Util qw/ openhandle /;
if (openhandle($filename)) ...
```

I totally forgot to first check Scalar::Util!

**Comment by perlpunk** [comment] 2016-02-21 20:03
created #42 (Scalar::Util)

**Comment by perlpunk** [comment] 2016-02-22 20:25
YAML::XS released today; thank you =)

**Closed by perlpunk** 2016-02-22 20:25 UTC

**Comment by GuiltyDolphin** [comment] 2016-02-23 16:23
@perlpunk Whoop! Thanks!
